# numpy

In [1]:
# Numerical arrays.
import numpy as np

## Resources

https://numpy.org/doc/stable/user/absolute_beginners.html

## Multidimensional Homogeneous Arrays

In [5]:
# A 2D array of integers.
X = np.array([[1, 2, 3], [4, 5, 6]])

# Show.
print(X)

[[1 2 3]
 [4 5 6]]


In [9]:
# Number of dimensions.
print(X.ndim)

2


In [10]:
# Shape of the array.
print(X.shape)

(2, 3)


In [11]:
# Type of the elements.
print(X.dtype)

int64


## Operations

In [18]:
# Two arrays.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Show.
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [19]:
# Adding constants.
A + 5

array([[6, 7],
       [8, 9]])

In [20]:
# Adding two arrays.
A + B

array([[ 6,  8],
       [10, 12]])

In [21]:
# Multiplying by a constant.
A * 2

array([[2, 4],
       [6, 8]])

In [22]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [24]:
# Matrix multiplication.
A @ B

array([[19, 22],
       [43, 50]])

## End